### ISSUE TITLE
PLC Settings

### ISSUE THREAD

**Issue by Preliy** [OpenCommissioning/OC_Assistant#11]
Project settings are not saved. When the settings window is reopened, the fields remain empty. 

![image](https://github.com/user-attachments/assets/243099a2-fea7-4433-a5d0-c535628c81d5)

The PLC instance is not found during generation.

**Comment by mika-engineering** [comment]
Happens with older xml files where the appropriate nodes are missing. Deleting the xml file and letting the assistant create a new one fixes the issue.
