### ISSUE TITLE
Installation Description for Plugins 

### ISSUE THREAD

**Issue by Preliy** [OpenCommissioning/OC_Assistant#13]
The current installation instructions for plugins in the OC Assistant documentation are incomplete. Users are not informed that plugins need to be placed in the same folder as the .exe file for proper functionality. Additionally, the OC Assistant .exe searches for plugins recursively from the root folder, which may cause confusion if plugins are not correctly placed.

Proposed Solution:
Update the installation instructions to include the following:

1. Plugins must be added to the same folder as the .exe file for correct detection.
2. Mention that the OC Assistant .exe searches recursively for plugins starting from the root folder.
3. Provide an example folder structure in the documentation to help users understand where plugins should be placed.

Mfg

**Comment by mika-engineering** [comment]
The readme file has been adjusted. Still needs updates after we release the pugins. Issue will stay open.
