### ISSUE TITLE
OC.Assistant_v1.5.2.zip Windows Defender detects a virus

### ISSUE THREAD

**Issue by C-Morrison** [OpenCommissioning/OC_Assistant#14]
Windows defender detects OC.Assistant_v1.5.2.zip as a threat.
Threat detected - Trojan:Script/Wacatac.B!ml
Is it safe?

**Comment by mika-engineering** [comment]
Yes it is safe. There is of course no virus in the zip file.
We just don't use any code signing for the Assistant and therefore windows can't verify the executable.
If you are not sure about it, you can clone the source code from the master branch and build the application yourself.
You need the [.NET8 SDK](https://dotnet.microsoft.com/en-us/download/dotnet/8.0) to build the application.

**Comment by C-Morrison** [comment]
Thanks for the reply. If you haven't already I suggest you add a note in the documentation.
